# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# MakeLALayer.py
# Created on: 2017-03-27 21:41:55.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Roads_ND = "Roads_ND"
Location_Allocation = "Location-Allocation"

# Process: Make Location-Allocation Layer
arcpy.MakeLocationAllocationLayer_na(Roads_ND, "Location-Allocation", "Minutes", "FACILITY_TO_DEMAND", "MINIMIZE_IMPEDANCE", "1", "", "LINEAR", "1", "10", "", "ALLOW_DEAD_ENDS_AND_INTERSECTIONS_ONLY", "", "NO_HIERARCHY", "STRAIGHT_LINES", "1", "")

