# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# SolveLA.py
# Created on: 2017-03-29 09:34:53.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Location_Allocation = "Location-Allocation"
Location_Allocation__2_ = Location_Allocation
Solve_Succeeded = "false"

# Process: Solve
arcpy.Solve_na(Location_Allocation, "SKIP", "TERMINATE", "")

